### PR TITLE
Add support for passing arguments to sourced file

### PR DESCRIPTION
**Pull request by gkrantz**
This PR adds support for passing arguments and changes version to 1.1.3

Signed off by: Gustav Krantz gukrantz@microsoft.com

### CODE REVIEW

**Comment by agriffis** [comment]
Thanks, this seems interesting! Out of curiousity, how are you using this feature?

Regarding the code, I think it might only work for a single argument, and it would be nice to handle multiple arguments properly. Also, what would you think about adding some tests to `test_read.py` (baseline no args, one arg, multiple args with spaces)

**Comment by gkrantz** [comment]
> Thanks, this seems interesting! Out of curiousity, how are you using this feature?

I'm writing a python script that needs to call a bash script where environment variables are set.
At the end of the script I need the environment variables to be set when calling another bash script.
1. Call xyz.sh with an argument
2. Do python stuff
3. Call abc.sh which relies on environment variables set in 1.

> Regarding the code, I think it might only work for a single argument, and it would be nice to handle multiple arguments properly. 

Good catch. I added a few commits.
>Also, what would you think about adding some tests to test_read.py (baseline no args, one arg, multiple args with spaces)

I believe no args is already covered. I added test cases for one argument and for three arguments and arguments with space.

I changed so that arguments are passed as strings in a list to allow for arguments with spaces, if you prefer passing them as a string, changing the splitting function is an option. shlex.split() should work.

**Comment by agriffis** [comment]
> I changed so that arguments are passed as strings in a list to allow for arguments with spaces

This is the right approach. Space-separating quoted args is a detail of shell syntax—it's better to handle args as lists internally, and only deal with quoting and space-separation on the boundary. Kinda like Ned's [unicode sandwich](https://nedbatchelder.com/text/unipain.html).

I made some small changes and moved it to a separate pull request #2 so I can squash before merging. The most significant change is `args=None` in the function signature. Defaulting a kwarg to a mutable value is something to avoid in Python, since you can end up with mutations sticking around to ensuing calls. (Not that it would have happened with your code, but it's better to avoid the anti-pattern.)

Thanks for the pull request!

**Comment by agriffis** [comment]
Released as 1.2.0 at https://pypi.org/project/envbash/

Thanks again!

**Comment by gkrantz** [comment]
Thank you! 👍

**Pull request closed without merging**
